package ${entity.javaPackage};

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import ${entity.commonPackage}.vo.${entity.base?cap_first}VO;

/**
* This code is generated by bianwentao
* @author bianwentao
*
*/
public class ${entity.base?cap_first} {
    /********** attribute ***********/
<#list entity.properties as property>
    private ${property.javaType} ${property.propertyName};

</#list>
    /********** constructors ***********/
<#if entity.constructors>
    public ${entity.className}() {

    }

    public ${entity.className}(<#list entity.properties as property>${property.javaType} ${property.propertyName}<#if property_has_next>, </#if></#list>) {
    <#list entity.properties as property>
        this.${property.propertyName} = ${property.propertyName};
    </#list>
    }
</#if>

    /********** get/set ***********/
<#list entity.properties as property>
    public ${property.javaType} get${property.propertyName?cap_first}() {
        return ${property.propertyName};
    }

    public void set${property.propertyName?cap_first}(${property.javaType} ${property.propertyName}) {
        this.${property.propertyName} = ${property.propertyName};
    }

</#list>

    public ${entity.base?cap_first}VO toTarget(){
        return new ${entity.base?cap_first}VO(<#list entity.properties as property>${property.propertyName}<#if property_has_next>, </#if></#list>);
    }

}