package ${entity.javaPackage};

import ${entity.commonPackage}.domain.${entity.base?cap_first};

/**
* This code is generated by bianwentao
* @author bianwentao
*
*/
public class ${entity.base?cap_first}VO {
    /********** attribute ***********/
<#list entity.properties as property>
    private ${property.javaType} ${entity.base}${property.propertyName?cap_first};

</#list>
    /********** constructors ***********/
<#if entity.constructors>
    public ${entity.className}() {

    }

    public ${entity.className}(<#list entity.properties as property>${property.javaType} ${property.propertyName}<#if property_has_next>, </#if></#list>) {
    <#list entity.properties as property>
        this.${entity.base}${property.propertyName?cap_first} = ${property.propertyName};
    </#list>
    }
    public ${entity.className}(<#list entity.properties as property><#if property.propertyName !="id">${property.javaType} ${property.propertyName}<#if property_has_next>, </#if></#if></#list>) {
        <#list entity.properties as property><#if property.propertyName !="id">
        this.${entity.base}${property.propertyName?cap_first} = ${property.propertyName};
        </#if></#list>
    }
</#if>

    /********** get/set ***********/
<#list entity.properties as property>
    public ${property.javaType} get${entity.base?cap_first}${property.propertyName?cap_first}() {
        return ${entity.base}${property.propertyName?cap_first};
    }

    public void set${entity.base?cap_first}${property.propertyName?cap_first}(${property.javaType} ${property.propertyName}) {
        this.${entity.base}${property.propertyName?cap_first} = ${property.propertyName};
    }

</#list>


    public ${entity.base?cap_first} toSource() {
    ${entity.base?cap_first} ${entity.base} = new ${entity.base?cap_first}();
        <#list entity.properties as property>
        ${entity.base}.set${property.propertyName?cap_first}(${entity.base}${property.propertyName?cap_first});
        </#list>
    return ${entity.base};
    }


}